# Generated by Django 3.0.10 on 2021-04-12 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210410_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorNoAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('charged', models.TextField(max_length=1024, null=True)),
                ('address', models.TextField()),
                ('desired_involvement', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=70, null=True, verbose_name='Affiliation')),
                ('is_adult', models.BooleanField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
