# Generated by Django 3.0.10 on 2021-04-12 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210412_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdirector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Headmaster'),
        ),
    ]
