# Generated by Django 3.0.10 on 2021-04-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210412_0650'),
        ('users', '0015_mentornoauth'),
    ]

    operations = [
    ]
