# Generated by Django 3.0.10 on 2021-04-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20210412_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentornoauth',
            old_name='desired_involvement',
            new_name='additional_involvement',
        ),
        migrations.RemoveField(
            model_name='mentornoauth',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mentornoauth',
            name='charged',
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='application_submitted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='attended_training',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='completed_trainingModules',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='follow_up',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='headmaster_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='isIncomplete',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='isInterested',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='isStaff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='isinCoporateEmployeeProgram',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='leadmentor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='legal_notes_bymentor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='legal_notes_byreviewer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='mentorAdvisor_notes',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='mentor_application_video_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='metHeadmaster',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='metMentorAdvisor',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='nextLeadMentor_meetingInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='nextLeadMentor_meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='occupation',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='onetime_donated',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='recurring_donation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='referral_source',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Refferal'),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='terms_agreement',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='trainingNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='trainingScheduled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='vbb_chapter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='VBB Chapter'),
        ),
        migrations.AddField(
            model_name='mentornoauth',
            name='vetted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='programdirector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Headmaster'),
        ),
    ]
